#!/usr/bin/env bash
# print "Best School" 10 times using while loop.
# on 9th iteration, print "Hi" then "Best School"

i=1

while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i -eq 9 ]
  then
      echo "Hi"
  fi
  (( i++ ))
done
