#!/usr/bin/env bash
# print "Best School" 10 times using bash for loop
# on 4th iteration print "bad luck" on the 8th "Best School"

i=1
while [ $i -le 10 ]
do
  if [ $i -eq 4 ]
  then
      echo "bad luck"
  elif [ $i -eq 8 ]
  then
      echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
