#!/usr/bin/env bash
# print the time hours and minutes using while loop

minute=0
hour=0

while [ $hour -le 12 ]
do
  if [ $minute -eq 60 ]
  then
    (( minute = 0 ))
    (( hour++ ))
  fi

  if [ $minute -eq 0 ] && [ $hour -le 12 ]
  then
    echo "Hour:" $hour
  elif [ $hour -ne 13 ]
  then
    echo $minute
  fi

  (( minute++ ))
done
